import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 IMPORTANT: every doc belongs to exactly ONE sidebar. Listing a doc in a second
 sidebar removes it from the first. This file previously also defined a
 "blogSidebar", which claimed every backend/ and devops/ doc and left
 tutorialSidebar with only ai/langchain — so the navbar's "Leaning" item (which
 highlights only for docs in its own sidebar) went inactive on 9 of 10 pages.
 That sidebar was also unused: this file configures the DOCS plugin only, the
 blog plugin does not read it. Keep a single docs sidebar here.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'AI',
      items: [{type: 'autogenerated', dirName: 'ai'}],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [{type: 'autogenerated', dirName: 'backend'}],
    },
    {
      type: 'category',
      label: 'DevOps',
      items: [
        'devops/helm',
        'devops/linux',
        {
          // Hand-ordered to follow the CKS exam curriculum, not alphabetically.
          type: 'category',
          label: 'CKS',
          items: [
            'devops/cks/cluster-setup',
            'devops/cks/cluster-hardening',
            'devops/cks/system-hardening',
            'devops/cks/minimize-microservice-vulnerabilities',
            'devops/cks/supply-chain-security',
            'devops/cks/monitoring-logging-runtime-security',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
