import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Blog sidebar organized by folder name
  blogSidebar: [
    {
      type: 'category',
      label: 'Backend',
      items: [
        {type: 'autogenerated', dirName: 'backend'},
      ],
    },
    {
      type: 'category',
      label: 'DevOps',
      items: [
        'devops/helm',
        'devops/linux',
        {
          type: 'category',
          label: 'CKS',
          items: [
            'devops/cks/cluster-setup',
            'devops/cks/cluster-hardening',
            'devops/cks/system-hardening',
            'devops/cks/minimize-microservice-vulnerabilities',
            'devops/cks/supply-chain-security',
            'devops/cks/monitoring-logging-runtime-security',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
