/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx,md,mdx}',
    './docs/**/*.{md,mdx}',
    './blog/**/*.{md,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': 'var(--primary-container)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'surface-container-low': 'var(--surface-container-low)',
        'on-tertiary': 'var(--on-tertiary)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'surface-bright': 'var(--surface-bright)',
        'on-error': 'var(--on-error)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'error': 'var(--error)',
        'surface-variant': 'var(--surface-variant)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'tertiary-container': 'var(--tertiary-container)',
        'background': 'var(--background)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'inverse-surface': 'var(--inverse-surface)',
        'on-primary': 'var(--on-primary)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface': 'var(--surface)',
        'error-container': 'var(--error-container)',
        'secondary': 'var(--secondary)',
        'on-error-container': 'var(--on-error-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'outline-variant': 'var(--outline-variant)',
        'on-background': 'var(--on-background)',
        'surface-container': 'var(--surface-container)',
        'inverse-primary': 'var(--inverse-primary)',
        'on-secondary': 'var(--on-secondary)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'on-surface': 'var(--on-surface)',
        'primary-fixed': 'var(--primary-fixed)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'primary': 'var(--primary)',
        'outline': 'var(--outline)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'surface-dim': 'var(--surface-dim)',
        'on-primary-container': 'var(--on-primary-container)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-tint': 'var(--surface-tint)',
        'secondary-container': 'var(--secondary-container)',
        'tertiary': 'var(--tertiary)',
        'accent-coral': 'var(--accent-coral)',
        'accent-orange': 'var(--accent-orange)',
        'ink-navy': 'var(--ink-navy)',
        'coral-red': 'var(--coral-red)',
        'minty-blue': 'var(--minty-blue)',
        'canvas-offwhite': 'var(--canvas-offwhite)',
      },
      spacing: {
        'container-max': '1200px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'section-gap': '120px',
        'gutter': '24px',
      },
      fontFamily: {
        "headline-lg-mobile": ["Bricolage Grotesque"],
        "headline-xl": ["Bricolage Grotesque"],
        "headline-lg": ["Bricolage Grotesque"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false, // Prevent Tailwind preflight from breaking Docusaurus defaults
  },
};
